project/urls.py
from django.contrib import admin
from django.urls import path, include
from simpleapp.views import *
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView
from rest_framework import routers

# router = routers.DefaultRouter()
# router.register(r'products', ProductViewset)
# router.register(r'categories', CategoryViewset)



urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include('simpleapp.urls')),
    path('products/', include('simpleapp.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    # path('products/', include('simpleapp.urls')),
    # path('api/', include(router.urls)),
    # YOUR PATTERNS
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    # Optional UI:
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

    # path('multiply/', multiply),
    # path('pages/', include('django.contrib.flatpages.urls')),
    # path('', include('simpleapp.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('accounts/', include("accounts.urls")),

# ]

simpleapp/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.cache import cache
from django.utils.translation import gettext as _
from django.utils.translation import pgettext_lazy # импортируем ленивый геттекст с подсказкой

class Material(models.Model):
    """Наименование материала"""
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Материал'
        verbose_name_plural = 'Материалы'

class Product(models.Model):
    """Товар"""
    name = models.CharField(max_length=200, unique=True, verbose_name=_('Name')) # названия товаров не должны повторяться
    description = models.CharField(max_length=200, verbose_name=_('Description'))
    quantity = models.IntegerField(validators=[MinValueValidator(0, 'Quantity should be >= 0.0')], verbose_name=_('Quantity'))
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE, related_name='products', verbose_name=_('Category')) # все продукты в категории будут доступны через поле products, поле категории будет ссылаться на модель категории
    # materials = models.ForeignKey(to='Material', on_delete=models.CASCADE)
    price = models.FloatField(validators=[MinValueValidator(0.0, 'Price should be >= 0.0')], verbose_name=_('Price'))
    is_activate = models.BooleanField(default=True)

    @property
    def on_stock(self):
        """Отображение наличия/отсутствия товара на складе"""
        return self.quantity > 0
    def get_absolute_url(self):
        """Отображение конкретной страницы после создания товара"""
        return reverse('product_detail', args=[str(self.id)]) # с помощью reverse указываем не путь типа /products/, а название пути

    def save(self, *args, **kwargs):
        """Сохранение объекта"""
        super().save(*args, **kwargs) # вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'product-{self.pk}') # удаляем его из кэша, чтобы сбросить его

    def __str__(self):
        """Строковое представление"""
        return f'{self.name.title()}: {self.description[:50]}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

class ProductMaterial(models.Model):
    """Промежуточная таблица для связки Продукта и Материала - Состав продукта"""
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    material = models.ForeignKey(Material, on_delete=models.CASCADE)

class Category(models.Model):
    """Категория, к которой будет привязываться товар"""
    name = models.CharField(max_length=100, unique=True, help_text=_('category name'))

    def __str__(self):
        return self.name.title()

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

class Subscription(models.Model):
    """Список категорий, на которые подписан пользователь"""
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
        verbose_name=pgettext_lazy('help text for Subscription model', 'This is the help text'),
    )

templates/product.html
<!--  наследуемся от шаблона default_backup.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load i18n %}

<!-- Название у нас будет Product -->
{% block title %}
{{ product.name }}
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}
<h2>{{ product.name|censor }}</h2>
<div>{% trans 'Category' %}: {{ product.category }}<br>
{% trans 'Description' %}: {{ product.description|censor }} <br>
{% trans 'In stock' %}: {{ product.quantity }} {% trans 'unit' %}.<br>
{% trans 'Price' %}: {{product.price }}₽ <br><br>
</div>

{% endblock content %}

templates/product_delete.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Delete product' %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>{% trans 'Delete' %} "{{ object.name }}"?</p>
    <input type="submit" value="{% trans 'Delete' %}" />
</form>
{% endblock content %}

templates/product_edit.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% block content %}
<h1>{% trans 'Product' %}</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }} {# форма, отображающаяся на странице #}
    {% comment 'Comment' %}
    <p>{% trans 'Info' %}</p>
    {% endcomment %}
    <input type="submit" value="{% trans 'Save' %}" />
</form>
{% endblock content %}

templates/products.html
{% extends 'flatpages/default.html' %}

{% load i18n %}
{% load custom_filters %} <!-- подключение кастомных фильтров-->
{% load custom_tags %}
{% load math_filters %}
{% load static %}

<!-- Название у нас будет products -->
{% block title %}
online_store
{% endblock title %}

{% block header %}
<header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">{% trans 'Online store' %}</h1>
                    <p class="lead fw-normal text-white-50 mb-0">{% trans 'Profitable offers' %}</p>
                </div>
            </div>
        </header>
{% endblock header %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>{% trans 'All products' %}</h1>

<section class="py-5">
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    {% if products %}
                        {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name|censor }}</h5>
                                    <!-- Product price-->
                                    {{ product.price }}₽
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="http://127.0.0.1:8000/products/{{ product.id }}">{% trans 'More details' %}</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}
    </section>

<!-- Форма с инпутами-->
<!--<form action="" method="get">-->
<!--       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}-->
<!--       {{ filterset.form.as_p }}-->
<!--       {# Добавим кнопку отправки данных формы #}-->
<!--       <input type="submit" value="Найти" />-->
<!--   </form>-->

<h3>{{ next_sale|default_if_none:"{% trans 'We will inform you about the sale later!' %}" }}</h3>

<h2>{% trans 'Additional information' %}</h2>
<hr>
<br>
<!-- Проверка прав доступа-->
{% if perms.simpleapp.add_product %}
<a href="{% url 'product_create' %}">{% trans 'Add product' %}</a>
{% endif %}

<!-- Выводим товары в наличии-->
{% if products %}

<table cellpadding="5">
    <tr> <!-- Добавляем строку-->
        <td>{% trans 'Name' %}</td>
        <td>{% trans 'Description' %}</td>
        <td>{% trans 'Category' %}</td>
        <td>{% trans 'Price' %}</td>
        <td>{% trans 'Quantity' %}</td>
        {# Условие получается составным #}
        {% if perms.simpleapp.change_product or perms.simpleapp.delete_product %}
        <td>{% trans 'Actions' %}</td>
        {% endif %}
    </tr>
    <!-- Для каждого товара будет генерироваться новая строчка, т.е. новый HTML-код, который указан в теле цикла. -->
    {% for product in products %}
    <tr class="{% cycle 'row-1' 'row-2' %}">
        <td>{{ product.name|censor }}</td>
        <td>{{ product.description|censor|truncatewords:2 }}</td>
        <td>{{ product.category.name|truncatewords:2 }}</td> {# default_if_none:'Без категории' #}
        <td>{{ product.price }}₽</td>
        <td style="text-align: center;">{{ product.quantity }} шт.</td>
        <td>
            {# Доступ для каждой ссылки проверяется отдельно #}
            {% if perms.simpleapp.change_product %}
            <a href="{% url 'product_update' pk=product.id %}">{% trans 'Edit' %}</a>
            <span>|</span>
            {% endif %}
            {% if perms.simpleapp.delete_product %}
            <a href="{% url 'product_delete' product.id %}">{% trans 'Delete' %}</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
<!--    {{ products }}-->
{% else %}
<!-- Если товара нет, то сообщаем об этом-->
<h4>{% trans 'No products!' %}</h4>
{% endif %}
<br>

{# Информация о предыдущих страницах #}
<div>
{% if page_obj.has_previous %} <!-- Если у объекта, в котором содержится информация о текущей странице, существует предыдущая страница-->
<a href="?{% url_replace page=1 %}">1</a> <!-- Формируем ссылку внизу страницы с адресом ?page=1 -->
{% if page_obj.previous_page_number != 1 %} <!-- Если у объекта, в котором содержится информация о текущей странице, номер предыдущей страницы не равен 1 -->
... <!-- Выводим троеточие-->
<a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a> <!-- Выводим сслыку снизу страницы с номером предыдущей страницы-->
{% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }} <!-- Выводим номер текущей страницы-->

{# Информация о следующих страницах #}
{% if page_obj.has_next %} <!-- Если в объекте, в котором содержится информация о текущей странице, существует следующая страница-->
<a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a> <!-- Указываем ссылку снизу страницы с номером следующей страницы-->
{% if paginator.num_pages != page_obj.next_page_number %} <!-- Если количество страницы не равно номеру следующей страницы-->
... <!-- Выводим троеточие-->
<a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>  <!-- Указываем ссылку снизу страницы на общее количество страниц-->
{% endif %}
{% endif %}
</div>

{% endblock content %}

templates/products_backup.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- подключение кастомных фильтров-->
{% load custom_tags %}
{% load math_filters %}
{% load static %}

<!-- Название у нас будет products -->
{% block title %}
online_store
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все товары</h1>

{# Добавляем форму, которая объединяет набор полей, отправляемых в запросе #}
<form action="" method="get" >
    {{ filterset.form.non_field_errors }} {# вывод ошибок, не относящихся к полям формы #}

    {{ filterset.form.name__icontains.errors }} {# вывод ошибок, относящихся к полю поиска по названию товара #}
    <input
        id="{{ filterset.form.name__icontains.id }}"
        name="{{ filterset.form.name__icontains.name }}"
        class="form-control"
        placeholder="Поиск"
    >
    <input type="submit" class="mt-3 btn-primary" value="Найти" />
</form>

<!-- Форма с инпутами-->
<!--<form action="" method="get">-->
<!--       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}-->
<!--       {{ filterset.form.as_p }}-->
<!--       {# Добавим кнопку отправки данных формы #}-->
<!--       <input type="submit" value="Найти" />-->
<!--   </form>-->

<h3>{{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }}</h3>
<hr>

<!-- Проверка прав доступа-->
{% if perms.simpleapp.add_product %}
<a href="{% url 'product_create' %}">Добавить товар</a>
{% endif %}


<!-- Выводим товары в наличии-->
{% if products %}

<table cellpadding="5">
    <tr> <!-- Добавляем строку-->
        <td>Название</td>
        <td>Описание</td>
        <td>Категория</td>
        <td>Цена</td>
        <td>Количество</td>
        {# Условие получается составным #}
        {% if perms.simpleapp.change_product or perms.simpleapp.delete_product %}
        <td>Действия</td>
        {% endif %}
    </tr>
    <!-- Для каждого товара будет генерироваться новая строчка, т.е. новый HTML-код, который указан в теле цикла. -->
    {% for product in products %}
    <div class="col mb-5">
        <div class="card h-100">
            <!-- Product image-->
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">{{ product.name }}</h5>
                    <!-- Product price-->
                    {{ product.price|currency:"usd" }}
                </div>

            </div>
                            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="http://127.0.0.1:8000/products/{{product.id}}">Перейти</a></div>
            </div>
        </div>
    </div>
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.description|truncatewords:2 }}</td>
        <td>{{ product.category.name|truncatewords:2 }}</td>
        <td>{{ product.price|currency:"usd" }}</td>
        <td style="text-align: center;">{{ product.quantity }}</td>
        <td>
            {# Доступ для каждой ссылки проверяется отдельно #}
            {% if perms.simpleapp.change_product %}
            <a href="{% url 'product_update' pk=product.id %}">Изменить</a>
            <span>|</span>
            {% endif %}
            {% if perms.simpleapp.delete_product %}
            <a href="{% url 'product_delete' product.id %}">Удалить</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
<!--    {{ products }}-->
{% else %}
<!-- Если товара нет, то сообщаем об этом-->
<h4>Товаров нет!</h4>
{% endif %}

{% block pagination %}
{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %} <!-- Если у объекта, в котором содержится информация о текущей странице, существует предыдущая страница-->
<a href="?{% url_replace page=1 %}">1</a> <!-- Формируем ссылку внизу страницы с адресом ?page=1 -->
{% if page_obj.previous_page_number != 1 %} <!-- Если у объекта, в котором содержится информация о текущей странице, номер предыдущей страницы не равен 1 -->
... <!-- Выводим троеточие-->
<a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a> <!-- Выводим сслыку снизу страницы с номером предыдущей страницы-->
{% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }} <!-- Выводим номер текущей страницы-->

{# Информация о следующих страницах #}
{% if page_obj.has_next %} <!-- Если в объекте, в котором содержится информация о текущей странице, существует следующая страница-->
<a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a> <!-- Указываем ссылку снизу страницы с номером следующей страницы-->
{% if paginator.num_pages != page_obj.next_page_number %} <!-- Если количество страницы не равно номеру следующей страницы-->
... <!-- Выводим троеточие-->
<a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>  <!-- Указываем ссылку снизу страницы на общее количество страниц-->
{% endif %}
{% endif %}
{% endblock pagination %}

{% endblock content %}

templates/products_bckup.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %} <!-- подключение кастомных фильтров-->
{% load custom_tags %}
{% load math_filters %}
{% load static %}

<!-- Название у нас будет products -->
{% block title %}
online_store
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
<h1>Все товары</h1>

{# Добавляем форму, которая объединяет набор полей, отправляемых в запросе #}
<form action="" method="get" >
    {{ filterset.form.non_field_errors }} {# вывод ошибок, не относящихся к полям формы #}

    {{ filterset.form.name__icontains.errors }} {# вывод ошибок, относящихся к полю поиска по названию товара #}
    <input
        id="{{ filterset.form.name__icontains.id }}"
        name="{{ filterset.form.name__icontains.name }}"
        class="form-control"
        placeholder="Поиск"
    >
    <input type="submit" class="mt-3 btn-primary" value="Найти" />
</form>

<!-- Форма с инпутами-->
<!--<form action="" method="get">-->
<!--       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}-->
<!--       {{ filterset.form.as_p }}-->
<!--       {# Добавим кнопку отправки данных формы #}-->
<!--       <input type="submit" value="Найти" />-->
<!--   </form>-->

<h3>{{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }}</h3>
<hr>

<!-- Проверка прав доступа-->
{% if perms.simpleapp.add_product %}
<a href="{% url 'product_create' %}">Добавить товар</a>
{% endif %}


<!-- Выводим товары в наличии-->
{% if products %}

<table cellpadding="5">
    <tr> <!-- Добавляем строку-->
        <td>Название</td>
        <td>Описание</td>
        <td>Категория</td>
        <td>Цена</td>
        <td>Количество</td>
        {# Условие получается составным #}
        {% if perms.simpleapp.change_product or perms.simpleapp.delete_product %}
        <td>Действия</td>
        {% endif %}
    </tr>
    <!-- Для каждого товара будет генерироваться новая строчка, т.е. новый HTML-код, который указан в теле цикла. -->
    {% for product in products %}
    <div class="col mb-5">
        <div class="card h-100">
            <!-- Product image-->
            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
            <!-- Product details-->
            <div class="card-body p-4">
                <div class="text-center">
                    <!-- Product name-->
                    <h5 class="fw-bolder">{{ product.name }}</h5>
                    <!-- Product price-->
                    {{ product.price|currency:"usd" }}
                </div>

            </div>
                            <!-- Product actions-->
            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="http://127.0.0.1:8000/products/{{product.id}}">Перейти</a></div>
            </div>
        </div>
    </div>
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.description|truncatewords:2 }}</td>
        <td>{{ product.category.name|truncatewords:2 }}</td>
        <td>{{ product.price|currency:"usd" }}</td>
        <td style="text-align: center;">{{ product.quantity }}</td>
        <td>
            {# Доступ для каждой ссылки проверяется отдельно #}
            {% if perms.simpleapp.change_product %}
            <a href="{% url 'product_update' pk=product.id %}">Изменить</a>
            <span>|</span>
            {% endif %}
            {% if perms.simpleapp.delete_product %}
            <a href="{% url 'product_delete' product.id %}">Удалить</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>
<!--    {{ products }}-->
{% else %}
<!-- Если товара нет, то сообщаем об этом-->
<h4>Товаров нет!</h4>
{% endif %}

{% block pagination %}
{# Информация о предыдущих страницах #}
{% if page_obj.has_previous %} <!-- Если у объекта, в котором содержится информация о текущей странице, существует предыдущая страница-->
<a href="?{% url_replace page=1 %}">1</a> <!-- Формируем ссылку внизу страницы с адресом ?page=1 -->
{% if page_obj.previous_page_number != 1 %} <!-- Если у объекта, в котором содержится информация о текущей странице, номер предыдущей страницы не равен 1 -->
... <!-- Выводим троеточие-->
<a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a> <!-- Выводим сслыку снизу страницы с номером предыдущей страницы-->
{% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }} <!-- Выводим номер текущей страницы-->

{# Информация о следующих страницах #}
{% if page_obj.has_next %} <!-- Если в объекте, в котором содержится информация о текущей странице, существует следующая страница-->
<a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a> <!-- Указываем ссылку снизу страницы с номером следующей страницы-->
{% if paginator.num_pages != page_obj.next_page_number %} <!-- Если количество страницы не равно номеру следующей страницы-->
... <!-- Выводим троеточие-->
<a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>  <!-- Указываем ссылку снизу страницы на общее количество страниц-->
{% endif %}
{% endif %}
{% endblock pagination %}

{% endblock content %}

templates/subscriptions.html
{% extends 'flatpages/default.html' %}
{% load i18n %}

{% block title %}
{% trans 'Subscribtions' %}
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>{% trans 'Subscribe' %}</button>
                    <button name="action" value="unsubscribe">{% trans 'Unsubscribe' %}</button>
                {% else %}
                    <button name="action" value="subscribe">{% trans 'Subscribe' %}</button>
                    <button disabled>{% trans 'Unsubscribe' %}</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}

templates/swagger-ui.html
<!DOCTYPE html>
<html>
 <head>
   <title>Swagger</title>
   <meta charset="utf-8"/>
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
 </head>
 <body>
   <div id="swagger-ui"></div>
   <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
   <script>
   const ui = SwaggerUIBundle({
       url: "/static/openapi-schema.yml",
       dom_id: '#swagger-ui',
       presets: [
         SwaggerUIBundle.presets.apis,
         SwaggerUIBundle.SwaggerUIStandalonePreset
       ],
       layout: "BaseLayout",
       requestInterceptor: (request) => {
         request.headers['X-CSRFToken'] = "{{ csrf_token }}"
         return request;
       }
     })
   </script>
 </body>
</html>